language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "nightly"
install:
# Use K2fov bleeding-edge master version to include its bugfixes
- pip install git+git://github.com/KeplerGO/K2fov@add-dates
- python setup.py install
script:
- py.test
